loader: Handle note files missing top-level keys
Release note files should look like this:

  issues:
  - |
    Some text here.

However, it's possible to make a mistake and create a release note
missing the top-level key:

  - |
    Some text here.

If you do this, reno fails with a cryptic error which Sphinx will bubble
up with zero context:

  AttributeError: 'list' object has no attribute 'items'

Make this failure more obvious.

Change-Id: I488d14bc1134a38d4f76ed5f5368c84db8e39df3
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
Story: 1670421
Task: 42802